kind: pipeline
type: kubernetes
name: default

steps:
  - name: kaniko-build
    image: gcr.io/kaniko-project/executor:v1.12.0-debug  # Use the debug version, it supports ARM
    environment:
      DOCKERFILE: Dockerfile
      CONTEXT: /workspace
      DOCKER_REGISTRY:  
    volumes:
      - name: docker-config
        path: /kaniko/.docker
    commands:
      - /kaniko/executor --context $DRONE_WORKSPACE --destination registry-docker-registry:5000/x:latest

volumes:
  - name: docker-config
    temp: {}