kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: kaniko
  image: gcr.io/kaniko-project/executor:latest
  environment:
    DOCKER_REGISTRY: <your-docker-registry>
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  arguments:
  - /kaniko/executor --context . --no-push
