kind: pipeline
type: kubernetes
name: default

steps:
- name: kaniko
  image: gcr.io/kaniko-project/executor:latest
  environment:
    DOCKER_REGISTRY: <your-docker-registry>
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
  - /kaniko/executor --context . --destination $DOCKER_REGISTRY/hello-world:latest

- name: deploy
  image: kubectl
  commands:
  - kubectl apply -f k8s/deployment.yaml