kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: kaniko
  image: plugins/kaniko
  environment:
    DOCKER_REGISTRY: hub.docker.com
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
  - pwd
