kind: pipeline
type: kubernetes
name: default

steps:
  - name: kaniko-build
    image: gcr.io/kaniko-project/executor:v1.12.0-debug  # Use the debug version, it supports ARM
    environment:
      DOCKERFILE: Dockerfile
      CONTEXT: /workspace
    volumes:
      - name: docker-config
        path: /kaniko/.docker
    commands:
      - /kaniko/executor --context $$CI_WORKSPACE --dockerfile $$DOCKERFILE --no-push

      

volumes:
  - name: docker-config
    temp: {}