
when:
- event: push
  branch: master
steps:
- name: publish
  image: woodpeckerci/plugin-kaniko
  settings:
    registry: registry-docker-registry.default.svc:5000
    repo: registry-docker-registry/test
    tags: ${CI_COMMIT_SHA}
    cache: true
    skip_tls_verify: true # set to true for testing registries ONLY with self-signed certs
    insecure-registry: true
    build_args:
    - COMMIT_SHA=${CI_COMMIT_SHA}
    - COMMIT_AUTHOR_EMAIL=${CI_COMMIT_AUTHOR_EMAIL}
